# Generated by Django 5.2.8 on 2025-12-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=20, unique=True)),
                ('extension', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
