# Generated by Django 5.2.8 on 2025-12-05 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_cafe_en_tu_taza', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=20, unique=True)),
                ('extension', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=45)),
                ('receptor', models.CharField(max_length=45)),
                ('numero_de_factura', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('forma_de_pago', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('importe_total', models.IntegerField()),
                ('descuentos', models.CharField(blank=True, max_length=5, null=True)),
                ('impuestos', models.IntegerField()),
                ('cantidad_adeudada', models.IntegerField()),
                ('condiciones_de_pago', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(unique=True)),
                ('cedula', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('inventario', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Farms',
        ),
        migrations.AddField(
            model_name='farmpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.post'),
        ),
        migrations.AddField(
            model_name='farm',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.producer'),
        ),
        migrations.AddField(
            model_name='productfarm',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.farm'),
        ),
        migrations.AddField(
            model_name='productfarm',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_cafe_en_tu_taza.product'),
        ),
    ]
